// Elements
export const recordSelectInput = (numValue) => {
    return `input[name="selections"][value="${numValue}"]`
} 
export const tableOddRow = 'tr[class="table__row table__body-row odd"]'
export const tableRow = 'tr[role="row"]'
export const tableFilter = 'input[class="sheet__search"]'
export const tableEmptySearch = 'td[class="dataTables_empty"]'
export const tablePages = 'a[aria-controls="DataTables_Table_0"]'
export const selectDisplayNum = 'select[name="DataTables_Table_0_length"]'
export const detailMenuPanel = 'div[class="menu"]'
export const sideRowInfo = 'div[class="details__data-container"]'
export const detailsSchedule = 'a[id="update-schedule-tab"]'
export const detailsAgreement = 'a[id="update-agreements-tab"]'
export const detailsFinance = 'a[id="update-financial-tab"]'
export const detailsFiles = 'a[id="update-files-tab"]'
export const detailsOthers = 'a[id="update-others-tab"]'
export const detailCloseIcon = 'img[title="Close side panel"]'
export const detailChangeLog = 'img[title="Show Changelog"]'
export const fullViewIcon = 'img[title="Full screen details"]'
export const tableFullRow = 'tr[class="details-table__row"]'
export const iconInfoFull = 'a[id="fullScreenDetailsInformationTab-tab"]'
export const iconScheduleFull = 'a[id="fullScreenDetailsRealisation-tab"]'
export const iconAgreeFull = 'a[id="fullScreenDetailsAgreements-tab"]'
export const iconFinFull = 'a[id="fullScreenDetailsFinancial-tab"]'
export const iconFileFull = 'a[id="fullScreenDetailsFiles-tab"]'
export const iconOtherFull = 'a[id="fullScreenDetailsOther-tab"]'
export const tableSchedule = 'table[class="table table-sm text-center mt-2"]'
export const detailTable = 'table[class="details-table"]'
export const iconFullClose = 'img[title="Exit"]'
export const buttonSaveEdit = 'button[type="Submit"]'
export const buttonEditFull = 'img[title="Edit"]'
export const editInput = 'input[class="select2-search__field"]'
export const editNewCreated = 'span[class="alert-message"]'
export const richTextEditor = 'div[aria-label="Rich Text Editor, main"] p'
export const createSelPrio = 'span[id="select2-id_priority-container"]'
export const editInputApi = 'input[id="id_api"]'
export const editPM = 'span[id="select2-id_project_manager-container"]'
export const editPMBApp = 'input[id="id_pmb_approval"]'
export const editDossReady = 'input[id="id_dossier_ready"]'
export const editAgreeSign = 'input[id="id_agreement_signature"]'
export const editEOU = 'input[id="id_agreement_number_eou"]'
export const editPBudget = 'input[id="id_project_budget"]'
export const editRegBudget = 'input[id="id_registration_budget"]'
export const editOtherPM = 'span[id="select2-id_product_manager-container"]'
export const recordsSelectAll = 'input[class="table__select table__select-all"]'

// URLs
export const projectSite = 'http://127.0.0.1:8000/projects/'
// Other data
export const titleSite = 'PMDB'
export const timeWait = 30000
export const shortTime = 5000
export const managerMarcinF = 'Marcin Feder'
export const managerMaciej = 'Maciej'
export const managerAleksN = 'Aleksandra Norek'
export const managerPiwo = 'Maciej piwowarski'
export const managerJR = 'Justyna Rogowska'
export const managerBG = 'Bartłomiej Grzywaczyk'
export const managerBLG = 'Bartlomiej Grzywaczyk'
export const managerBg = 'Bartłomiej grzywaczyk'
export const managerWM = 'Wojciech Maszewski'
export const managerWm = 'Wojciech maszewski'
export const tableSelectedColor = 'rgba(73, 196, 161, 0.5)'
export const emptySearchMessage = 'No matching records found'
export const pageColor1 = '#37474f'
export const pageColor2 = 'rgb(55, 71, 79)'
export const itemIDValue = (num) => {
    return `\n  \n    \n      \n\n      Id\n    \n      ${num}\n    \n  \n`
}
export const noFilesMess = 'No files available. Edit project for files upload.'
export const noChangeMess = 'No changes have been made to this project yet.'
export const ckeChangeTest = 'changeTest'
export const editNewDate = '2020-05-30{enter}'
