// This file contains data for login page tests
// Login Elements
export const contactButton = 'span[class="icon contact-icon"]'
export const documentButton = 'span[class="icon documentation-icon"]'
export const signInButton = 'button[id="signInDropdownMenuButton"]'
export const inputUserName = 'input[id="id_username"]'
export const inputPassword = 'input[id="id_password"]'
export const addProject = 'img[title="Add project"]'
export const loginError = 'div[class="alert alert-info"]'
export const signupButton = 'button[id="signUpDropdownMenuButton"]'
export const newUserMenu = 'div[aria-labelledby="signUpDropdownMenuButton"]'
export const newUserName = 'input[placeholder="First Name"]'
export const newUserLast = 'input[placeholder="Last Name"]'
export const newUserEmail = 'input[placeholder="Email"]'
export const inputPassNew = 'input[placeholder="Password"]'
export const inputPassConfNew = 'input[placeholder="Confirm Password"]'
export const logoutIcon = 'img[title="Logout"]'
// Login URLs
export const loginSite = 'http://127.0.0.1:8000/'
export const loginURL = 'http://127.0.0.1:8000/accounts/login/'
// Login Other data
export const correctUser = 'maciej'
export const correctPass = '123'
export const incorrectUser = 'dabro123'
export const incorrectPass = 'dupa'
export const messageError = '\n                        Please enter a correct username and password. Note that both fields may be case-sensitive.\n                    '
export const newFirstName = 'New'
export const newLastName = 'User'
export const newEmail = 'new.user@adamed.com'
export const newPassword = 'NewPass123'