export const projectsLicenseURL = 'http://127.0.0.1:8000/projects/licensein/'
export const projectsRdURL = 'http://127.0.0.1:8000/projects/rd/'
export const prescriptionFSMP = 'FSMP'
export const prescriptionOTC = 'OTC'
export const marketPoland = 'Poland'
export const marketRussia = 'Russia'

export const projectsPFHeader1 = 'th[aria-label=" Pharmaceutical form : activate to sort column ascending"]'
export const projectsPFHeader2 = 'th[aria-label=" Pharmaceutical form : activate to sort column descending"]'
export const projectsPCHeader1 = 'th[aria-label=" Prescription Category : activate to sort column ascending"]'
export const projectsPCHeader2 = 'th[aria-label=" Prescription Category : activate to sort column descending"]'
export const projectsMarHeader1 = 'th[aria-label=" Market : activate to sort column ascending"]'
export const projectsMarHeader2 = 'th[aria-label=" Market : activate to sort column descending"]'

export const projectsSort1 = '\n    \n    \n    \n            Acetic Acid/Cal ...\n            Oral Drops Solution\n            \n      \n    Justyna RogowskaOral drops solutionFSMP1mg; 2mgVietnam'
export const projectsSort2 = '\n    \n    \n    \n            Vorinostat\n            Solution For Injection And Infusion\n            \n      \n    Bartlomiej GrzywaczykSolution for injection and infusionFood Supplement250mg/20mlGeorgia'
export const projectSort5 = '\n    \n    \n    \n            Nicotinamide/Pa ...\n            Bath Emulsion\n            \n      \n    Maciej piwowarskiBath emulsionMedical Device20mgItaly'
export const projectSort6 = '\n    \n    \n    \n            Ascorbic Acid/B ...\n            N/A\n            \n      \n    Bartłomiej grzywaczykn/aRx drug0,5mgUkraine'
export const projectSort7 = '\n    \n    \n    \n            Althaea Officin ...\n            Nebuliser Suspension\n            \n      \n    Bartłomiej grzywaczykNebuliser suspensionBiosimilar drug20mgTurkmenistan'
export const projectSort8 = '\n    \n    \n    \n            Conium Maculatu ...\n            Dispersible Tablet\n            \n      \n    Wojciech MaszewskiDispersible tabletRx drug10ml/mlBelarus'
export const projectSort9 = '\n    \n    \n    \n            Body Cream\n            Powder For Solution For Injection\n            \n      \n    Wojciech maszewskiPowder for solution for injectionMedical Device0,001 mg/mlUzbekistan'
export const projectSort10 = '\n    \n    \n    \n            Ascorbic Acid/A ...\n            Effervescent Powder\n            \n      \n    Bartlomiej GrzywaczykEffervescent powderRx drug7,5mg/10mlTajikistan'
export const projectSort11 = '\n    \n    \n    \n            Magnesium/Multi ...\n            Intravenous Infusion\n            \n      \n    Piotr PotaczekIntravenous infusionOTC drug2 mg/mlAzerbaijan'
export const projectSort12 = '\n    \n    \n    \n            Acetic Acid/Cal ...\n            Oral Drops Solution\n            \n      \n    Justyna RogowskaOral drops solutionFSMP1mg; 2mgVietnam'
export const registrationMAH = '\n  \n    \n      \n\n      Registration Strategy\n    \n      MAH transfer\n    \n  \n'
export const scheduleComment = '\n  \n    \n      \n      Schedule Comments\n    \n      Społeczny układ palec relacja gwałtowny tłumaczyć kłopot. Podstawa dodatkowy brzeg. Opowiadać zachodni rejon skała herbata. Wiosna gmina studiować epoka.\n    \n  \n'