// This file contains data for templates page tests
// Templates Elements
export const templateDetailProjectName = 'a[id="details_s_name"]'
export const templateDetailChanges = 'div[class="details__changes-container"]'
export const templateDetailInfo = 'a[data-project-tab-type="informations"]'
export const templateContHeader = 'div[class="details__container-header"]'
export const templateShowChange = 'img[alt="history of changes"]'
export const templateInfo = 'a[id="update-informations-tab"]'
export const templateFinance = 'a[id="update-financial-tab"]'
export const templateChangelog = 'img[alt="history of changes"]'
export const templateAgreeF = 'a[id="fullScreenDetailsAgreements-tab"]'
export const templateOtherF = 'a[id="fullScreenDetailsOther-tab"]'
export const templateTableCell = 'td[class="details-table__cell"]'
export const templateTScheduleFull = 'div[class="details__data-row"]'
export const templateEditDetail = 'img[title="Edit template"]'
export const templateEditFull = 'img[title="Edit"]'
export const templateCloseFull = 'img[title="Exit"]'
export const templateSaveEdit = 'button[type="Submit"]'
export const templateAddNew = 'img[title="Add template"]'
export const templateSelSource = 'select[id="id_source"]'
export const templateSelPro = 'span[id="select2-id_project_manager-container"]'
export const templateSelMol = 'span[id="select2-id_molecule-container"]'
export const templateSelStr = 'input[id="id_strength"]'
export const templateSelPF = 'span[id="select2-id_pharmaceutical_form-container"]'
export const templateSelTA = 'span[id="select2-id_therapeutical_area-container"]'
export const templateSelPrio = 'span[id="select2-id_priority-container"]'
export const templateSelATC = 'span[id="select2-id_atc3_or_otc3-container"]'
export const templateCreate = 'input[value="Create template"]'
export const templateInput = 'input[class="select2-search__field"]'
export const templateNewSuccess = 'span[class="alert-message"]' 
export const templateFirst = 'div[class="project_name_api"]'
export const templateInputApi = 'input[id="id_api"]'
export const templatePMBApp = 'input[id="id_pmb_approval"]'
export const templateIPCX = 'div[aria-label="Rich Text Editor, main"]'
export const templateAgreeNote = 'input[id="id_notice_period"]'
export const templateSuppPeriod = 'input[id="id_supply_period"]'
export const templatePBudget = 'input[id="id_project_budget"]'
export const templateRefInput = 'input[id="id_reference_product"]'
export const templatePNHeader1 = 'th[aria-label=" Project Name : activate to sort column ascending"]'
export const templatePNHeader2 = 'th[aria-label=" Project Name : activate to sort column descending"]'
export const templateMHeader1 = 'th[aria-label=" Molecule : activate to sort column ascending"]'
export const templateMHeader2 = 'th[aria-label=" Molecule : activate to sort column descending"]'
export const templatePMHeader1 = 'th[aria-label=" Project Manager : activate to sort column ascending"]'
export const templatePMHeader2 = 'th[aria-label=" Project Manager : activate to sort column descending"]'
export const templatePSHeader1 = 'th[aria-label=" Strength : activate to sort column ascending"]'
export const templatePSHeader2 = 'th[aria-label=" Strength : activate to sort column descending"]'
export const templateTCell = 'td[class=" table__cell"]'
export const templateCKEditorPar = 'div[aria-label="Rich Text Editor, main"] p'

// Template 99 details
export const tepmateSpanField = 'span[class="details__data-value"]'
export const templateSpanDetail = 'span[class="details__data-key"]'
export const templateIdValue = '\n      99\n    '
export const templateConfidentValue = '\n      —\n    '
export const templateProNameValue = '\n      Serenoa Repens/Tribulus Terrestris/Urtica Dioica--Lotion\n    '
export const templateMoleculeValue = '\n      Serenoa Repens/Tribulus Terrestris/Urtica Dioica\n    '
export const templateApiValue = '\n      uniwersytet\n    '
export const templatePharmFormValue = '\n      Lotion\n    '
export const templateStrengthValue = '\n      0.05mg/ml\n    '
export const templateSourceValue = '\n      License-in\n    '
export const templateProManValue = '\n      Marcin Feder\n    '
export const templateAreaValue = '\n      Analgesics\n    '
export const templatePriorityValue = '\n      B\n    '
export const templateAtcOtcValue = '\n      J05C Hiv Antivirals\n    '
export const templateLicenseValue = '\n      Biomed Lublin\n    '
export const templateNLicenseValue = '\n      —\n    '

// Template details fields
export const templateIdField = '\n      \n\n      Id'
export const templateConfidentField = '\n      \n\n      Confidential'
export const templateProNameField = '\n      \n\n      Project Name'
export const templateMoleculeField = '\n      \n\n      Molecule'
export const templateApiField = '\n      \n\n      Api'
export const templatePharmFormField = '\n      \n\n      Pharmaceutical Form'
export const templateStrengthField = '\n      \n\n      Strength'
export const templateSourceField = '\n      \n\n      Source'
export const templateProManField = '\n      \n\n      Project Manager'
export const templateAreaField = '\n      \n\n      Therapeutical Area'
export const templatePriorityField = '\n      \n\n      Priority'
export const templateAtcOtcField = '\n      \n\n      Atc3 Or Otc3'
export const templateLicenseField = '\n      \n\n      Licensor'
export const templateNLicenseField = '\n      \n\n      New Licensor'

// Template 99 schedule
export const templateAgreeValue = '\n      Agreement signed\n      \n        \n        2020-05-21\n        \n      \n      \n        \n        2020-05-22\n        \n      \n    '
export const templateDsvValue = '\n      Availability in DSV\n      \n        \n        2020-06-15\n        \n      \n      \n        \n        2020-06-01\n        \n      \n    '
export const templateMexValue = '\n      2020-06-18\n    '

// Template schedule fields
export const templateAgreeField = 'Agreement signed'
export const templateDsvField = 'Availability in DSV'
export const templateMexField = '\n      \n      Mex'

// Template 99 agreement
export const templateMaqValue = '\n      Wy katastrofa smutek metoda. Siedem należeć wina dziecięcy działać Ziemia ciepły.\nKrólowa ziemniak może obwód. Istota stawiać epoka czynnik liść decyzja.\n    '
export const templateDeliveryValue = '\n      DAP\n    '
export const templateVarValue = '\n      System wcześnie jakiś dość bogactwo. 6 kilometr działać czoło operacja Dania polegać. Norma przeciwko poczta podróż lek oprzeć środowisko od.\n    '

// Template agreement fields
export const templateMaqField = '\n      \n      Maq'
export const templateDeliveryField = '\n      \n      Delivery Terms'
export const templateVarField = '\n      \n      Variation Cost'

// Template 99 finance
export const templateCogsValue = '\n      Rano okno medycyna chemiczny. Połowa spadać wybierać potrzebować wymagać.\n    '
export const templateLBudgetValue = '\n      351 644,26\n    '

// Template finance fields
export const templateCogsField = '\n      Cogs'
export const templateLBudgetField = '\n      License Budget'

// Template 99 others
export const templateLRefProValue = '\n      państwo\n    '
export const templateLContactValue = '\n      Listopad Kościół ściana drużyna pisanie. Taki czoło natychmiast handlowy transport dotyczyć. Ciecz czyn prędkość radio że przeprowadzać współczesny region. Jako ciekawy długo.\n    '

// Template others fields
export const templateLRefProField = '\n      Reference Product'
export const templateLContactField = '\n      Contact Persons'

// Template Full screen
export const templateTextId = 'Id'
export const templateValueId = '99'
export const templateTextSource = 'Source'
export const templateValueSource = 'License-in'
export const templateTextPrior = 'Priority'
export const templateValuePrior = 'B'
export const templateTextMApp = 'MA granted date'
export const templateValueMApp = '\n      MA granted date\n      \n        \n        2020-06-13\n        \n      \n      \n        \n        2020-06-07\n        \n      \n    '
export const templateTextDex = 'Dex'
export const templateValueDex = '\n    \n      \n      Dex\n    \n      2020-06-01\n    \n  '
export const templateTextRC = 'Reconciliation Comment'
export const templateValueRC = 'Broda temu ulegać oglądać. Stopień ucho tamten sposób stopa zaraz. Bieg urodziny ogień tydzień igła gałąź instytucja osioł.'
export const templateTextCPD = 'Competitive Product Definition'
export const templateValueCPD = 'Sądowy przyrząd usterka drewniany. Wykonywanie obecny powolny bok sam gabinet wschodni. Wierny pamiętać nauczyciel jezioro czasownik okropny.'
export const templateTextCogs = 'Cogs'
export const templateVelueCogs = 'Rano okno medycyna chemiczny. Połowa spadać wybierać potrzebować wymagać.'
export const templateTextPBC = 'Project Budget Currency'
export const templateValuePBC = 'Lotnisko nos krzyż. Czoło umysł treść wyrażenie dużo dwa.\nDać wiadomość dokonywać pociąg wywoływać bok wąski. Do czyn kłaść znaleźć głód częściowo kultura. Pieśń wciąż dach brzeg jaki mysz dziób.'
export const templateTextFile = 'No files available. Edit project for files upload.'

// Templates URLs
export const allTemplatesSite = 'http://127.0.0.1:8000/templates/'
export const licenseTemplatesSite = 'http://127.0.0.1:8000/templates/licensein/'
export const rdTemplatesSite = 'http://127.0.0.1:8000/templates/rd/'

// Templates Other data
export const formCreamy = 'Cream'
export const formHerbal = 'Herbal'
export const nameBifi = 'Bifidobacterium'
export const nameMagnesium = 'Magnesium'
export const molecouleChromium = 'Chromium'
export const molecouleZinc = 'Zinc'
export const strength10 = '10mg/10ml'
export const strength05 = '0.05mg/ml'
export const emptySearchText = 'No matching records found'
export const nonExistentText1 = 'NoQuery1'
export const nonExistentText2 = 'NoQuery2'
export const templateNoChange = 'No changes have been made to this project yet.'
export const templateFull = 'Details of template'
export const template1Prop = '1-Propanol'
export const templateSuccessNfo = 'Success! ProjectTemplate created'
export const templateSuccessUpd = 'Success! ProjectTemplate updated'
export const templateNeurology = 'Neurology'
export const templateAntimeta = 'Antimetabolites'
export const templateSort1 = '\n    \n    \n    \n            Acetic Acid/Cal ...\n            Oral Drops Solution\n            Acetic Acid/Calcium/Gelatin/Magnesium/Potassium/SodiumJustyna Rogowska1mg; 2mg'
export const templateSort2 = '\n    \n    \n    \n            Vorinostat\n            Solution For Injection And Infusion\n            VorinostatBartlomiej Grzywaczyk250mg/20ml'
export const templateSort3 = '\n    \n    \n    \n            Althaea Officin ...\n            Nebuliser Suspension\n            Althaea Officinalis/Ascorbic Acid/Matricaria Chamomilla/Rubus Idaeus/Salvia Officinalis/Sambucus Nig ...Bartłomiej grzywaczyk20mg'
export const templateSort4 = '\n    \n    \n    \n            Conium Maculatu ...\n            Dispersible Tablet\n            Conium Maculatum/Iodine/Iron Ferric/Populus Tremuloides/Serenoa RepensWojciech Maszewski10ml/ml'
export const templateSort5 = '\n    \n    \n    \n            Body Cream\n            Powder For Solution For Injection\n            Body CreamWojciech maszewski0,001 mg/ml'
export const templateSort6 = '\n    \n    \n    \n            Ascorbic Acid/A ...\n            Effervescent Powder\n            Ascorbic Acid/Astaxanthin/Betacarotene/Camellia Sinensis/Copper/Cysteine/Hyaluronic Acid/Lycopene/Ma ...Bartlomiej Grzywaczyk7,5mg/10ml'
export const templateTextApproval = '\n      PMB approval Date\n      \n        \n        2020-05-30\n        \n      \n      \n        \n        2020-06-17\n        \n      \n    '
export const templateChangeTest = 'changeTest'
export const templateAgreeData1 = '\n      2016\n    '
export const templateAgreeData2 = '\n      10.0\n    '
export const templateFinanceData1 = '\n      99,00\n    '
export const templateOthersData1 = '\n      changeTest\n    '
export const checkTemplateId = (num) => {
    return `\n    \n      \n\n      Id\n    \n      ${num}\n    \n  `
}
export const templateSelectedColor = 'rgba(73, 196, 161, 0.5)'
export const templatedClickColor = 'rgba(236, 225, 72, 0.5)'