// This file contains data for templates page tests
// Templates Elements
export const selectRecordDisplay = 'select[name="DataTables_Table_0_length"]'
export const templateRows = 'tr[role="row"]'
export const templatePages = 'a[aria-controls="DataTables_Table_0"]'
export const templateSearchFilter = 'input[class="sheet__search"]'
export const templateEmptySearch = 'td[class="dataTables_empty"]'
export const templateSelectInput = (numValue) => {
    return `input[name="selections"][value="${numValue}"]`
} 
export const templateSelectAll = 'input[class="table__select table__select-all"]'
export const templateDetailMenu = 'div[class="menu"]'
export const templateDetailClose = 'img[title="Close side panel"]'
export const templateDetailProjectName = 'a[id="details_s_name"]'
export const templateDetailChanges = 'div[class="details__changes-container"]'
export const templateDetailInfo = 'a[data-project-tab-type="informations"]'
export const templateDetailSchedule = 'a[id="update-schedule-tab"]'
export const templateDetailAgree = 'a[id="update-agreements-tab"]'
export const templateDetailFinancial = 'a[id="update-financial-tab"]'
export const templateDetailOthers = 'a[id="update-others-tab"]'
export const templateContHeader = 'div[class="details__container-header"]'
export const templateShowChange = 'img[alt="history of changes"]'
export const templateInfo = 'a[id="update-informations-tab"]'
export const templateSchedule = 'a[id="update-schedule-tab"]'
export const templateAgreement = 'a[id="update-agreements-tab"]'
export const templateFinance = 'a[id="update-financial-tab"]'
export const templateOther = 'a[id="update-others-tab"]'
// Template 99 details
export const tepmateSpanField = 'span[class="details__data-value"]'
export const templateSpanDetail = 'span[class="details__data-key"]'
export const templateIdValue = '\n      99\n    '
export const templateConfidentValue = '\n      —\n    '
export const templateProNameValue = '\n      Serenoa Repens/Tribulus Terrestris/Urtica Dioica--Lotion\n    '
export const templateMoleculeValue = '\n      Serenoa Repens/Tribulus Terrestris/Urtica Dioica\n    '
export const templateApiValue = '\n      uniwersytet\n    '
export const templatePharmFormValue = '\n      Lotion\n    '
export const templateStrengthValue = '\n      0.05mg/ml\n    '
export const templateSourceValue = '\n      License-in\n    '
export const templateProManValue = '\n      Marcin Feder\n    '
export const templateAreaValue = '\n      Analgesics\n    '
export const templatePriorityValue = '\n      B\n    '
export const templateAtcOtcValue = '\n      J05C Hiv Antivirals\n    '
export const templateLicenseValue = '\n      Biomed Lublin\n    '
export const templateNLicenseValue = '\n      —\n    '
// Template details fields
export const templateIdField = '\n      \n\n      Id'
export const templateConfidentField = '\n      \n\n      Confidential'
export const templateProNameField = '\n      \n\n      Project Name'
export const templateMoleculeField = '\n      \n\n      Molecule'
export const templateApiField = '\n      \n\n      Api'
export const templatePharmFormField = '\n      \n\n      Pharmaceutical Form'
export const templateStrengthField = '\n      \n\n      Strength'
export const templateSourceField = '\n      \n\n      Source'
export const templateProManField = '\n      \n\n      Project Manager'
export const templateAreaField = '\n      \n\n      Therapeutical Area'
export const templatePriorityField = '\n      \n\n      Priority'
export const templateAtcOtcField = '\n      \n\n      Atc3 Or Otc3'
export const templateLicenseField = '\n      \n\n      Licensor'
export const templateNLicenseField = '\n      \n\n      New Licensor'
// Template 99 schedule
export const templateAgreeValue = '\n      Agreement signed\n      \n        \n        2020-05-21\n        \n      \n      \n        \n        2020-05-22\n        \n      \n    '
export const templateDsvValue = '\n      Availability in DSV\n      \n        \n        2020-06-15\n        \n      \n      \n        \n        2020-06-01\n        \n      \n    '
export const templateMexValue = '\n      2020-06-18\n    '
// Template schedule fields
export const templateAgreeField = 'Agreement signed'
export const templateDsvField = 'Availability in DSV'
export const templateMexField = '\n      \n      Mex'
// Template 99 agreement
export const templateMaqValue = '\n      Wy katastrofa smutek metoda. Siedem należeć wina dziecięcy działać Ziemia ciepły.\nKrólowa ziemniak może obwód. Istota stawiać epoka czynnik liść decyzja.\n    '
export const templateDeliveryValue = '\n      DAP\n    '
export const templateVarValue = '\n      System wcześnie jakiś dość bogactwo. 6 kilometr działać czoło operacja Dania polegać. Norma przeciwko poczta podróż lek oprzeć środowisko od.\n    '
// Template agreement fields
export const templateMaqField = '\n      \n      Maq'
export const templateDeliveryField = '\n      \n      Delivery Terms'
export const templateVarField = '\n      \n      Variation Cost'
// Template 99 finance
export const templateCogsValue = '\n      Rano okno medycyna chemiczny. Połowa spadać wybierać potrzebować wymagać.\n    '
export const templateLBudgetValue = '\n      351 644,26\n    '
// Template finance fields
export const templateCogsField = '\n      Cogs'
export const templateLBudgetField = '\n      License Budget'
// Template 99 others
export const templateLRefProValue = '\n      państwo\n    '
export const templateLContactValue = '\n      Listopad Kościół ściana drużyna pisanie. Taki czoło natychmiast handlowy transport dotyczyć. Ciecz czyn prędkość radio że przeprowadzać współczesny region. Jako ciekawy długo.\n    '
// Template others fields
export const templateLRefProField = '\n      Reference Product'
export const templateLContactField = '\n      Contact Persons'
// Templates URLs
export const allTemplatesSite = 'http://127.0.0.1:8000/templates/'
export const licenseTemplatesSite = 'http://127.0.0.1:8000/templates/licensein/'
export const rdTemplatesSite = 'http://127.0.0.1:8000/templates/rd/'
// Templates Other data
export const formCreamy = 'Cream'
export const formHerbal = 'Herbal'
export const nameBifi = 'Bifidobacterium'
export const nameMagnesium = 'Magnesium'
export const molecouleChromium = 'Chromium'
export const molecouleZinc = 'Zinc'
export const strength10 = '10mg/10ml'
export const strength05 = '0.05mg/ml'
export const emptySearchText = 'No matching records found'
export const nonExistentText1 = 'NoQuery1'
export const nonExistentText2 = 'NoQuery2'
export const project74Name = '\n      Colecalciferol/Fish/Folic Acid/Glycine Max/Iodine/Vitamin E--Orodispersible tablet\n    —'
export const project74Creation = '\n    Creation: Adrian Jasiński,\n    2020-05-08, 14:57:27\n  '
export const project74Modification = '\n    Modification: Adrian Jasiński,\n    2020-05-08, 14:57:27\n  '
export const project74HeadInfo = '\n                Project informations\n            '
export const project74HeadSchedule = '\n                Schedule\n            '
export const project74HeadAgree = '\n                Agreements\n            '
export const project74HeadFin = '\n                Financial\n            '
export const project74HeadOther = '\n                Others\n            '
